repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: fix-byte-order-marker
      - id: check-added-large-files
        args: ["--maxkb=2000"]
      - id: mixed-line-ending
  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.1
    hooks:
      # Go Mod Tidy
      - id: go-mod-tidy
      - id: go-mod-tidy-repo
      # Go Build
      - id: go-build-mod
      - id: go-build-repo-mod
      # Go Test
      - id: go-test-mod
      # Go Vet
      - id: go-vet
      # GoSec
      - id: go-sec-mod
      # StaticCheck
      - id: go-staticcheck-mod
      # StructSlop
      - id: go-structslop-mod
      # Formatters
      - id: go-fmt
      - id: go-fmt-repo
      - id: go-fumpt        # replaces go-fmt
      - id: go-fumpt-repo   # replaces go-fmt-repo
      - id: go-imports      # replaces go-fmt
      - id: go-imports-repo # replaces go-fmt-repo
      - id: go-returns      # replaces go-imports & go-fmt
      - id: go-returns-repo # replaces go-imports-repo & go-fmt-repo
      # Style Checkers
      - id: go-critic
      # GolangCI-Lint
      - id: golangci-lint
      - id: golangci-lint-mod
      - id: golangci-lint-repo-mod
