# !! Requires Pre-Commit
# !!    https://pre-commit.com
repos:
  # ==========================================================================
  # Golang Pre-Commit Hooks | https://github.com/tekwizely/pre-commit-golang
  # ==========================================================================
  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: master
    hooks:
      # Go Build
      -   id: go-build-mod
      -   id: go-build-repo-mod
      # Go Mod Tidy
      -   id: go-mod-tidy
      -   id: go-mod-tidy-repo
      # Go Test
      -   id: go-test-mod
      -   id: go-test-repo-mod
      # Go Vet
      -   id: go-vet
      # Revive
      -   id: go-revive
      # GoSec
      -   id: go-sec-mod
      -   id: go-sec-repo-mod
      # StaticCheck
      -   id: go-staticcheck-mod
      -   id: go-staticcheck-repo-mod
      # StructSlop
      -   id: go-structslop-mod
      -   id: go-structslop-repo-mod
      # Formatters
      -   id: go-fmt
      -   id: go-fmt-repo
      -   id: go-fumpt        # replaces go-fmt
      -   id: go-fumpt-repo   # replaces go-fmt-repo
      -   id: go-imports      # replaces go-fmt
      -   id: go-imports-repo # replaces go-fmt-repo
      -   id: go-returns      # replaces go-imports & go-fmt
      -   id: go-returns-repo # replaces go-imports-repo & go-fmt-repo
      #
      # Style Checkers
      #
      -   id: go-lint
      -   id: go-critic
      #
      # GolangCI-Lint
      # - Fast Multi-Linter
      # - Can be configured to replace MOST other hooks
      # - Supports repo config file for configuration
      # - https://github.com/golangci/golangci-lint
      #
      -   id: golangci-lint
      -   id: golangci-lint-mod
      -   id: golangci-lint-repo-mod
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: fix-encoding-pragma
        args: [--remove]
      - id: fix-byte-order-marker
      - id: check-added-large-files
        args: ['--maxkb=2000']
      - id: mixed-line-ending
